name: MERN CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  client-tests:
    name: Run Client Tests and Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint src

      - name: Run Tests
        run: npm run test -- --watchAll=false

  server-tests:
    name: Run Server Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Tests (if available)
        run: echo "No backend tests yet"